name: connecta
description: Simplify and streamline socket communication in Dart applications
version: 1.2.0
topics: [network, tls, tcp, wrapper]
repository: https://github.com/vsevex/connecta
issue_tracker: https://github.com/vsevex/connecta/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0

platforms:
  android:
  ios:
  linux:
  web:
  windows:
