name: connecta
description: A starting point for Dart libraries or applications.
version: 1.0.0-beta1
repository: https://github.com/vsevex/connecta

environment:
  sdk: ^3.1.2

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
